# Generated by Django 4.1.1 on 2022-12-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                ("product_desc", models.CharField(max_length=200)),
                ("product_image", models.ImageField(upload_to="images")),
            ],
        ),
    ]
