# Generated by Django 4.1.1 on 2022-12-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_number",
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
